### ISSUE TITLE
Tex display in markdown

### ISSUE THREAD

**Issue by astonzhang** [mli/gluon-tutorials-zh#2]
Thank @mli for making the Chinese tutorial of gluon available! 撒花~

Although some sections are still under construction, a common issue is that the current markdown cannot display tex ($tex contents$) properly, such as in:

https://github.com/mli/gluon-tutorials-zh/blob/master/chapter01_crashcourse/autograd.md
https://github.com/mli/gluon-tutorials-zh/blob/master/chapter01_crashcourse/linear-regression-scratch.md
https://github.com/mli/gluon-tutorials-zh/blob/master/chapter02_multilayer-neural-network/mlp-scratch.md

**Comment by mli** [comment]
github is not able to displace latex. but latex is supported in 

- markdown editor, suchas typora
- jupyter notebook
- rendered html at zh.gluon.ai

so i think it is fine for now
