### ISSUE TITLE
0.11 mxnet does NOT support Windows platform

### ISSUE THREAD

**Issue by shuren0806** [mli/gluon-tutorials-zh#6]
I am using 64-bit Windows 10, but hit the following issue: 

gluon-tutorials-zh>conda env create -f environment.yml
Fetching package metadata ...............

NoPackagesFoundError: Package missing in current win-64 channels:
  - mxnet >=0.11.1b20170902

from PyPI, I find that that latest mxnet 0.11.1b20170904 only support Linux and Mac.

even I remove the '>=0.11.1b20170902', it still cannot find any mxnet.

so my questions are:
1. do not know why mxnet is not found even I remove the version restriction?
    'pip install mxnet' can install a Windows mxnet. the version is 0.10.0.post2.
   I suspect that  0.10.0.post2 does not contains the new gluon feauture. 
2. Is there any way to build the 0.11 for Windows by myself? 
   or are there any points to any already pre-build by others?

thanks,
Sam

**Comment by szha** [comment]
The pip windows version is work-in-progress and will be released soon. An installation guide can be found [here](https://mxnet.incubator.apache.org/versions/master/get_started/windows_setup.html) though it may be slightly outdated. Both are expected to be addressed this week.

**Comment by zhreshold** [comment]
You can use `pip install mxnet --pre` on windows now.
Nightly build will be enabled in the near future so you can always get the up to date mxnet using pip

**Comment by shuren0806** [comment]
@zhreshold  it WORKS.  thanks!
